### ISSUE TITLE
[JENKINS-12124] random NoClassDefFoundError: hudson/plugins/analysis/core/AbstractProjectAction - Not all jobs loaded

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-15#4988]
<p>It sometimes happens, that upon fresh start of tomcat, not all Jobs/Projects are loaded.<br/>
Once logging in and clicking on "reload configuration from disk" this works w/o any error and all the missing jobs are there.<br/>
It seems to be random... and on another restart some other jobs are missing...<br/>
Any clue?</p>

<blockquote>
<p>INFO: Started all plugins<br/>
Dec 16, 2011 9:14:36 AM jenkins.InitReactorRunner$1 onAttained<br/>
INFO: Augmented all extensions<br/>
Dec 16, 2011 9:14:59 AM jenkins.InitReactorRunner$1 onTaskFailed<br/>
SEVERE: Failed Loading job XXXXXX<br/>
java.lang.NoClassDefFoundError: hudson/plugins/analysis/core/AbstractProjectAction<br/>
at java.lang.ClassLoader.defineClass1(Native Method)<br/>
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)<br/>
at java.lang.ClassLoader.defineClass(ClassLoader.java:616)<br/>
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)<br/>
at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)<br/>
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)<br/>
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)<br/>
at java.security.AccessController.doPrivileged(Native Method)<br/>
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)<br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:307)<br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:248)<br/>
at hudson.plugins.checkstyle.CheckStylePublisher.getProjectAction(CheckStylePublisher.java:128)<br/>
at hudson.tasks.BuildStepCompatibilityLayer.getProjectActions(BuildStepCompatibilityLayer.java:73)<br/>
at hudson.model.Project.createTransientActions(Project.java:208)<br/>
at hudson.model.AbstractProject.updateTransientActions(AbstractProject.java:602)<br/>
at hudson.model.AbstractProject.onLoad(AbstractProject.java:272)<br/>
at hudson.model.Project.onLoad(Project.java:88)<br/>
at hudson.model.Items.load(Items.java:115)<br/>
at jenkins.model.Jenkins$14.run(Jenkins.java:2364)<br/>
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)<br/>
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)<br/>
at jenkins.model.Jenkins$5.runTask(Jenkins.java:804)<br/>
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)<br/>
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)<br/>
at java.lang.Thread.run(Thread.java:662)<br/>
Caused by: java.lang.ClassNotFoundException: hudson.plugins.analysis.core.AbstractProjectAction<br/>
at java.net.URLClassLoader$1.run(URLClassLoader.java:202)<br/>
at java.security.AccessController.doPrivileged(Native Method)<br/>
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)<br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:307)<br/>
at java.lang.ClassLoader.loadClass(ClassLoader.java:248)<br/>
... 27 more<br/>
Dec 16, 2011 9:15:19 AM jenkins.InitReactorRunner$1 onAttained<br/>
INFO: Loaded all jobs<br/>
Dec 16, 2011 9:15:19 AM jenkins.InitReactorRunner$1 onAttained<br/>
INFO: Completed initialization</p></blockquote>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/myron.png" title="myron's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=myron">myron</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-12124" target="_blank">random NoClassDefFoundError: hudson/plugins/analysis/core/AbstractProjectAction - Not all jobs loaded</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/jglick.png" title="jglick's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>label(s)</b>: 1.532.3-rejected, classloader, hackathon-munich, random, threads
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-02-21T21:35:24+00:00
<li><b>votes</b>: 21
<li><b>watchers</b>: 27
<li><b>imported</b>: 2025-11-16
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>It sometimes happens, that upon fresh start of tomcat, not all Jobs/Projects are loaded.
Once logging in and clicking on "reload configuration from disk" this works w/o any error and all the missing jobs are there.
It seems to be random... and on another restart some other jobs are missing...
Any clue?</p>

<blockquote>
<p>INFO: Started all plugins
Dec 16, 2011 9:14:36 AM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Dec 16, 2011 9:14:59 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading job XXXXXX
java.lang.NoClassDefFoundError: hudson/plugins/analysis/core/AbstractProjectAction
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
        at hudson.plugins.checkstyle.CheckStylePublisher.getProjectAction(CheckStylePublisher.java:128)
        at hudson.tasks.BuildStepCompatibilityLayer.getProjectActions(BuildStepCompatibilityLayer.java:73)
        at hudson.model.Project.createTransientActions(Project.java:208)
        at hudson.model.AbstractProject.updateTransientActions(AbstractProject.java:602)
        at hudson.model.AbstractProject.onLoad(AbstractProject.java:272)
        at hudson.model.Project.onLoad(Project.java:88)
        at hudson.model.Items.load(Items.java:115)
        at jenkins.model.Jenkins$14.run(Jenkins.java:2364)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:804)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.ClassNotFoundException: hudson.plugins.analysis.core.AbstractProjectAction
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
        ... 27 more
Dec 16, 2011 9:15:19 AM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Dec 16, 2011 9:15:19 AM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization</p></blockquote></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Tomcat 6, JDK6, maven 3.0.3, SunOS, latest analysis* plugins, latest jenkins</code></li></ul>
<details><summary><i>3 attachments</i></summary>

- [jenkins-12124.log](https://issues.jenkins.io/secure/attachment/23329/jenkins-12124.log)
- [tomcat7-stderr.2013-07-10-no-errors.zip](https://issues.jenkins.io/secure/attachment/23917/tomcat7-stderr.2013-07-10-no-errors.zip)
- [tomcat7-stderr.2013-07-10-with-errors.zip](https://issues.jenkins.io/secure/attachment/23918/tomcat7-stderr.2013-07-10-with-errors.zip)
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/drulli.png" title="drulli's avatar" /> drulli's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=156958&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-156958">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Hmm, no idea what the problem might be. Could it be that you installed a new version of analysis-core when that happens? </p>
</pre>
</details>

</details>
<p>Hmm, no idea what the problem might be. Could it be that you installed a new version of analysis-core when that happens? </p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/nzhuk.jpg" title="nzhuk's avatar" /> nzhuk's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=157769&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-157769">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>I noticed the exact same problem here. Jenkins 1.447, latest analysis plugins (Static Analysis Utilities 1.37), Mac OS X 10.7.2. Reloading Jenkins configuration from disk seemed to worked around this problem.</p>
</pre>
</details>

</details>
<p>I noticed the exact same problem here. Jenkins 1.447, latest analysis plugins (Static Analysis Utilities 1.37), Mac OS X 10.7.2. Reloading Jenkins configuration from disk seemed to worked around this problem.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>andreas_schoen's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=159479&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-159479">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>We got the same stack trace here.</p>
<ul>
	<li>Reloading configuration from disk has NOT resolved the problem - I get the error each time on the same job.</li>
	<li>Update (downwards) from Jenkins ver. 1.450 to Jenkins ver. 1.437 (with restart) HAS resolved the issue.</li>
</ul>


</pre>
</details>

</details>
<p>We got the same stack trace here.</p>
<ul>
	<li>Reloading configuration from disk has NOT resolved the problem - I get the error each time on the same job.</li>
	<li>Update (downwards) from Jenkins ver. 1.450 to Jenkins ver. 1.437 (with restart) HAS resolved the issue.</li>
</ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>jacekw's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=160391&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-160391">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>And in version 1.454, upgraded from Hudson. It's blocker for us - every night Jenkins virtual machine is stopped for backup, after it's started, this issue happens, preventing night builds.</p>
</pre>
</details>

</details>
<p>And in version 1.454, upgraded from Hudson. It's blocker for us - every night Jenkins virtual machine is stopped for backup, after it's started, this issue happens, preventing night builds.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/myron.png" title="myron's avatar" /> myron's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=160401&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-160401">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>what exception are you now observing?
For me, with actual Jenkins 1.455 (as WAR) the "java.lang.NoClassDefFoundError: hudson/plugins/analysis/core/AbstractProjectAction" is gone (thanks Ulli).</p>

<p>Unfortunately, i'm now also seeing the "java.lang.NoClassDefFoundError: hudson/plugins/tasks/TasksProjectAction" - should this be a separate Bug?</p>

<p>Edit:
After several restarts, i now only have 10 jobs activated <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/> (from 70)
now i get more and more </p>
<blockquote>
<p>java.lang.NoClassDefFoundError: hudson/plugins/warnings/WarningsProjectAction
        at hudson.plugins.warnings.WarningsPublisher.getProjectAction(WarningsPublisher.java:229)
        at hudson.tasks.BuildStepCompatibilityLayer.getProjectActions(BuildStepCompatibilityLayer.java:73)
        at hudson.maven.MavenModuleSet.createTransientActions(MavenModuleSet.java:355)
        at hudson.model.AbstractProject.updateTransientActions(AbstractProject.java:603)
        at hudson.maven.MavenModuleSet.updateTransientActions(MavenModuleSet.java:342)
        at hudson.model.AbstractProject.onLoad(AbstractProject.java:273)
        at hudson.maven.MavenModuleSet.onLoad(MavenModuleSet.java:617)
        at hudson.model.Items.load(Items.java:115)
        at jenkins.model.Jenkins$15.run(Jenkins.java:2421)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
        at jenkins.model.Jenkins$6.runTask(Jenkins.java:840)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
Mar 19, 2012 3:01:20 PM jenkins.InitReactorRunner$1 onTaskFailed</p></blockquote>
<p>how can this be THAT random?</p>


<p>Edit2:
seems do have disappeared magically when upgrading to latest MavenCorePlugin + and latest FindBugs plugin...?!</p>
</pre>
</details>

</details>
<p>what exception are you now observing?<br/>
For me, with actual Jenkins 1.455 (as WAR) the "java.lang.NoClassDefFoundError: hudson/plugins/analysis/core/AbstractProjectAction" is gone (thanks Ulli).</p>

<p>Unfortunately, i'm now also seeing the "java.lang.NoClassDefFoundError: hudson/plugins/tasks/TasksProjectAction" - should this be a separate Bug?</p>

<p>Edit:<br/>
After several restarts, i now only have 10 jobs activated <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/> (from 70)<br/>
now i get more and more </p>
<blockquote>
<p>java.lang.NoClassDefFoundError: hudson/plugins/warnings/WarningsProjectAction<br/>
at hudson.plugins.warnings.WarningsPublisher.getProjectAction(WarningsPublisher.java:229)<br/>
at hudson.tasks.BuildStepCompatibilityLayer.getProjectActions(BuildStepCompatibilityLayer.java:73)<br/>
at hudson.maven.MavenModuleSet.createTransientActions(MavenModuleSet.java:355)<br/>
at hudson.model.AbstractProject.updateTransientActions(AbstractProject.java:603)<br/>
at hudson.maven.MavenModuleSet.updateTransientActions(MavenModuleSet.java:342)<br/>
at hudson.model.AbstractProject.onLoad(AbstractProject.java:273)<br/>
at hudson.maven.MavenModuleSet.onLoad(MavenModuleSet.java:617)<br/>
at hudson.model.Items.load(Items.java:115)<br/>
at jenkins.model.Jenkins$15.run(Jenkins.java:2421)<br/>
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)<br/>
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)<br/>
at jenkins.model.Jenkins$6.runTask(Jenkins.java:840)<br/>
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)<br/>
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)<br/>
at java.lang.Thread.run(Thread.java:662)<br/>
Mar 19, 2012 3:01:20 PM jenkins.InitReactorRunner$1 onTaskFailed</p></blockquote>
<p>how can this be THAT random?</p>


<p>Edit2:<br/>
seems do have disappeared magically when upgrading to latest MavenCorePlugin + and latest FindBugs plugin...?!</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>zlosch's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=161272&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-161272">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>We have the same issue here:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-none">SEVERE: Failed Loading job xxxxxxxxxxxxxxxx
java.lang.NoClassDefFoundError: hudson/plugins/findbugs/FindBugsProjectAction
	at hudson.plugins.findbugs.FindBugsPublisher.getProjectAction(FindBugsPublisher.java:147)
	at hudson.tasks.BuildStepCompatibilityLayer.getProjectActions(BuildStepCompatibilityLayer.java:73)
	at hudson.model.Project.createTransientActions(Project.java:208)
	at hudson.model.AbstractProject.updateTransientActions(AbstractProject.java:618)
	at hudson.model.AbstractProject.onLoad(AbstractProject.java:273)
	at hudson.model.Project.onLoad(Project.java:88)
	at hudson.model.Items.load(Items.java:115)
	at jenkins.model.Jenkins$15.run(Jenkins.java:2421)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
	at jenkins.model.Jenkins$6.runTask(Jenkins.java:840)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Apr 5, 2012 8:49:39 AM jenkins.InitReactorRunner$1 onTaskFailed
</pre>
</div></div>

<p>I increased the priority to 'blocker' because more and more jobs cannot be loaded. In this state Jenkins is unusable for us.</p>
</pre>
</details>

</details>
<p>We have the same issue here:</p>


<pre>
SEVERE: Failed Loading job xxxxxxxxxxxxxxxx
java.lang.NoClassDefFoundError: hudson/plugins/findbugs/FindBugsProjectAction
	at hudson.plugins.findbugs.FindBugsPublisher.getProjectAction(FindBugsPublisher.java:147)
	at hudson.tasks.BuildStepCompatibilityLayer.getProjectActions(BuildStepCompatibilityLayer.java:73)
	at hudson.model.Project.createTransientActions(Project.java:208)
	at hudson.model.AbstractProject.updateTransientActions(AbstractProject.java:618)
	at hudson.model.AbstractProject.onLoad(AbstractProject.java:273)
	at hudson.model.Project.onLoad(Project.java:88)
	at hudson.model.Items.load(Items.java:115)
	at jenkins.model.Jenkins$15.run(Jenkins.java:2421)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
	at jenkins.model.Jenkins$6.runTask(Jenkins.java:840)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Apr 5, 2012 8:49:39 AM jenkins.InitReactorRunner$1 onTaskFailed
</pre>

<p>I increased the priority to 'blocker' because more and more jobs cannot be loaded. In this state Jenkins is unusable for us.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>zlosch's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=161273&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-161273">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>The jobs can be loaded again after upgrading the findbugs plugin from 4.36 to 4.37</p>
</pre>
</details>

</details>
<p>The jobs can be loaded again after upgrading the findbugs plugin from 4.36 to 4.37</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/mhambidge.jpg" title="mhambidge's avatar" /> mhambidge's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=181382&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-181382">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>I'm uploading zipped logs from my server that appears to demonstrate the issue. I went ahead and enabled "ALL" level for the top level "hudson" log, so be warned that there is a lot of cruft in the log files. </p>

<p>tomcat7-stderr.2013-07-10-with-errors.zip - This log includes the "NoClassDefFoundError" for the hudson/plugins/analysis/core/AbstractProjectAction. I usually only see the error after restarting the actual server. My theory being that this causes a lot of churn (disk, cpu, etc.) when Tomcat comes up at this time and thus introduces different timing, allowing for the problem to occur (of course, there's always alternate explanations). Note that the problem is just easier to reproduce after a system reboot, but its not exclusive to it.</p>

<p>tomcat7-stderr.2013-07-10-no-errors.zip - I then restarted Tomcat and all the Jobs loaded without error.</p>
</pre>
</details>

</details>
<p>I'm uploading zipped logs from my server that appears to demonstrate the issue. I went ahead and enabled "ALL" level for the top level "hudson" log, so be warned that there is a lot of cruft in the log files. </p>

<p>tomcat7-stderr.2013-07-10-with-errors.zip - This log includes the "NoClassDefFoundError" for the hudson/plugins/analysis/core/AbstractProjectAction. I usually only see the error after restarting the actual server. My theory being that this causes a lot of churn (disk, cpu, etc.) when Tomcat comes up at this time and thus introduces different timing, allowing for the problem to occur (of course, there's always alternate explanations). Note that the problem is just easier to reproduce after a system reboot, but its not exclusive to it.</p>

<p>tomcat7-stderr.2013-07-10-no-errors.zip - I then restarted Tomcat and all the Jobs loaded without error.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>gotwarlost's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=195404&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-195404">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Thank you for looking into this issue with high priority. Hope to see a fix on LTS soon <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>
</pre>
</details>

</details>
<p>Thank you for looking into this issue with high priority. Hope to see a fix on LTS soon <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/dogfood.png" title="dogfood's avatar" /> dogfood's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=195547&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-195547">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Integrated in <span class="image-wrap" style=""><img src="http://ci.jenkins-ci.org/images/16x16/blue.png" style="border: 0px solid black" /></span> <a href="http://ci.jenkins-ci.org/job/jenkins_main_trunk/3192/" class="external-link" target="_blank" rel="nofollow noopener">jenkins_main_trunk #3192</a>
     <span class="error">&#91;FIXED JENKINS-12124&#93;</span> Occasionally errors loading plugin classes since it is expected that findClass (and findLoadedClass) are called under synchronization. (Revision 898f1f76a37e1c69cf38df718a5d3899544ebb44)</p>

<p>     Result = SUCCESS
Jesse Glick : <a href="https://github.com/jenkinsci/jenkins/commit/898f1f76a37e1c69cf38df718a5d3899544ebb44" class="external-link" target="_blank" rel="nofollow noopener">898f1f76a37e1c69cf38df718a5d3899544ebb44</a>
Files : </p>
<ul>
	<li>core/src/main/java/hudson/PluginManager.java</li>
	<li>core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java</li>
	<li>changelog.html</li>
	<li>core/src/main/java/hudson/ClassicPluginStrategy.java</li>
</ul>

</pre>
</details>

</details>
<p>Integrated in <span class="image-wrap" style=""><img src="http://ci.jenkins-ci.org/images/16x16/blue.png" style="border: 0px solid black" /></span> <a href="http://ci.jenkins-ci.org/job/jenkins_main_trunk/3192/" class="external-link" target="_blank" rel="nofollow noopener">jenkins_main_trunk #3192</a><br/>
     <span class="error">&#91;FIXED JENKINS-12124&#93;</span> Occasionally errors loading plugin classes since it is expected that findClass (and findLoadedClass) are called under synchronization. (Revision 898f1f76a37e1c69cf38df718a5d3899544ebb44)</p>

<p>     Result = SUCCESS<br/>
Jesse Glick : <a href="https://github.com/jenkinsci/jenkins/commit/898f1f76a37e1c69cf38df718a5d3899544ebb44" class="external-link" target="_blank" rel="nofollow noopener">898f1f76a37e1c69cf38df718a5d3899544ebb44</a><br/>
Files : </p>
<ul>
	<li>core/src/main/java/hudson/PluginManager.java</li>
	<li>core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java</li>
	<li>changelog.html</li>
	<li>core/src/main/java/hudson/ClassicPluginStrategy.java</li>
</ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/olivergondza.png" title="olivergondza's avatar" /> olivergondza's <a href="https://issues.jenkins.io/browse/JENKINS-12124?focusedId=198255&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-198255">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Fixed in 1.554. No need to backport.</p>
</pre>
</details>

</details>
<p>Fixed in 1.554. No need to backport.</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Originally duplicated by: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-15/issues?q=in%3Atitle%20JENKINS-16923">JENKINS-16923</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Originally duplicated by: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-15/issues?q=in%3Atitle%20JENKINS-12464">JENKINS-12464</a>]</i>
