### ISSUE TITLE
[JENKINS-26575] Running the reverse migrator after upgrading to 1.597 throws NoClassDefFoundError: javax/servlet/http/HttpServletRequest

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-15#12449]
<p>After upgrading to 1.597 from 1.588 on Windows </p>
<ul>
	<li>I cannot downgrade because trying to run the unmigrate script fails with:

<pre>
Exception in thread <span class="code-quote">"main"</span> java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
at hudson.Util.createSymlinkJava7(Util.java:1224)
at hudson.Util.createSymlink(Util.java:1118)
at jenkins.model.RunIdMigrator.unmigrateBuildsDir(RunIdMigrator.java:371
)
at jenkins.model.RunIdMigrator.unmigrateJobsDir(RunIdMigrator.java:320)
at jenkins.model.RunIdMigrator.main(RunIdMigrator.java:307)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
at java.net.URLClassLoader$1.run(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)
... 5 more
</pre></li>
</ul>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dhlight">dhlight</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-26575" target="_blank">Running the reverse migrator after upgrading to 1.597 throws NoClassDefFoundError: javax/servlet/http/HttpServletRequest</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/jglick.png" title="jglick's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2025-03-25T17:58:25+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-11-16
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading to 1.597 from 1.588 on Windows </p>
<ul>
	<li>I cannot downgrade because trying to run the unmigrate script fails with:
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Exception in thread <span class="code-quote">"main"</span> java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
        at hudson.Util.createSymlinkJava7(Util.java:1224)
        at hudson.Util.createSymlink(Util.java:1118)
        at jenkins.model.RunIdMigrator.unmigrateBuildsDir(RunIdMigrator.java:371
)
        at jenkins.model.RunIdMigrator.unmigrateJobsDir(RunIdMigrator.java:320)
        at jenkins.model.RunIdMigrator.main(RunIdMigrator.java:307)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)
        ... 5 more
</pre>
</div></div></li>
</ul>
</pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/gbhat.png" title="gbhat's avatar" /> gbhat's <a href="https://issues.jenkins.io/browse/JENKINS-26575?focusedId=453360&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-453360">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>This Jira can be closed as the unmigrate functionality was removed in <a href="https://github.com/jenkinsci/jenkins/pull/9092" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/9092</a></p>
</pre>
</details>

</details>
<p>This Jira can be closed as the unmigrate functionality was removed in <a href="https://github.com/jenkinsci/jenkins/pull/9092" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/9092</a></p>
