### ISSUE TITLE
[JENKINS-6437] No build possible after update

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-15#8207]
<p>After upgrading from 355 to 356 we could not get any builds startet but get:</p>

<p>Started by an SCM change<br/>
FATAL: hudson.util.jna.GNUCLibrary (initialization failure)<br/>
java.lang.NoClassDefFoundError: hudson.util.jna.GNUCLibrary (initialization failure)<br/>
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:140)<br/>
	at hudson.Util.createSymlink(Util.java:1000)<br/>
	at hudson.model.Run.run(Run.java:1242)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:122)</p>

<p>There used to be a similar issue (<a href="https://issues.jenkins.io/browse/JENKINS-4820" title="Build Fails on  PPC64/Linux with  IBM-JDK" class="issue-link" data-issue-key="JENKINS-4820"><del>JENKINS-4820</del></a>), current environment is similar</p>

<p>Linux xxx 2.6.18-194.el5 #1 SMP Tue Mar 16 22:03:12 EDT 2010 ppc64 ppc64 ppc64 GNU/Linux</p>

<p> /opt/ibm/java-ppc64-60/bin/java -version<br/>
java version "1.6.0"<br/>
Java(TM) SE Runtime Environment (build pxp6460sr8-20100409_01(SR8))<br/>
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux ppc64-64 jvmxp6460sr8-20100401_55940 (JIT enabled, AOT enabled)<br/>
J9VM - 20100401_055940<br/>
JIT  - r9_20100401_15339<br/>
GC   - 20100308_AA)<br/>
JCL  - 20100408_01</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=cdaszenies">cdaszenies</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-6437" target="_blank">No build possible after update</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/mindless.png" title="mindless's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=mindless">mindless</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>component(s)</b>: core
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2010-05-06T16:56:07+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-11-16
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading from 355 to 356 we could not get any builds startet but get:</p>

<p>Started by an SCM change
FATAL: hudson.util.jna.GNUCLibrary (initialization failure)
java.lang.NoClassDefFoundError: hudson.util.jna.GNUCLibrary (initialization failure)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:140)
	at hudson.Util.createSymlink(Util.java:1000)
	at hudson.model.Run.run(Run.java:1242)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:122)</p>

<p>There used to be a similar issue (<a href="https://issues.jenkins.io/browse/JENKINS-4820" title="Build Fails on  PPC64/Linux with  IBM-JDK" class="issue-link" data-issue-key="JENKINS-4820"><del>JENKINS-4820</del></a>), current environment is similar</p>

<p>Linux xxx 2.6.18-194.el5 #1 SMP Tue Mar 16 22:03:12 EDT 2010 ppc64 ppc64 ppc64 GNU/Linux</p>

<p> /opt/ibm/java-ppc64-60/bin/java -version
java version "1.6.0"
Java(TM) SE Runtime Environment (build pxp6460sr8-20100409_01(SR8))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux ppc64-64 jvmxp6460sr8-20100401_55940 (JIT enabled, AOT enabled)
J9VM - 20100401_055940
JIT  - r9_20100401_15339
GC   - 20100308_AA)
JCL  - 20100408_01</p>
</pre>
</details>
</details>
