### ISSUE TITLE
[JENKINS-10059] NoClassDefFoundError: org/apache/tools/ant/types/selectors/TokenizedPath after upgrading to 1.417

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-15#4575]
<p>After upgrading to Jenkins 1.417 (from 1.416) the following error appeared in the console output while executing a job on our z/Linux build slave.</p>

<pre>
ERROR: Failed to archive test reports
hudson.util.IOException2: remote file operation failed: /home<span class="code-comment">/*****/</span>jenkins/workspace/****** at hudson.remoting.Channel@eae9cc:Runtime_zLinux_Slave
	at hudson.FilePath.act(FilePath.java:754)
	at hudson.FilePath.act(FilePath.java:740)
	at hudson.tasks.junit.JUnitParser.parse(JUnitParser.java:83)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:123)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:135)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
	at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:664)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:639)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:617)
	at hudson.model.Build$RunnerImpl.post2(Build.java:161)
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:586)
	at hudson.model.Run.run(Run.java:1400)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:146)
Caused by: java.io.IOException: Remote call on Runtime_zLinux_Slave failed
	at hudson.remoting.Channel.call(Channel.java:676)
	at hudson.FilePath.act(FilePath.java:747)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: org/apache/tools/ant/types/selectors/TokenizedPath
	at org.apache.tools.ant.DirectoryScanner.scan(DirectoryScanner.java:869)
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:490)
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:451)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:105)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:87)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:1980)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:283)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:452)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
	at java.util.concurrent.FutureTask.run(FutureTask.java:149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:897)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:919)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:736)
</pre>

<p>The JRE used on the build slave is "IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux s390x-64".</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fredg">fredg</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-10059" target="_blank">NoClassDefFoundError: org/apache/tools/ant/types/selectors/TokenizedPath after upgrading to 1.417</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>label(s)</b>: java-ibm, z/linux
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2018-08-23T17:40:06+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-11-16
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading to Jenkins 1.417 (from 1.416) the following error appeared in the console output while executing a job on our z/Linux build slave.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">ERROR: Failed to archive test reports
hudson.util.IOException2: remote file operation failed: /home<span class="code-comment">/*****/</span>jenkins/workspace/****** at hudson.remoting.Channel@eae9cc:Runtime_zLinux_Slave
	at hudson.FilePath.act(FilePath.java:754)
	at hudson.FilePath.act(FilePath.java:740)
	at hudson.tasks.junit.JUnitParser.parse(JUnitParser.java:83)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:123)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:135)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
	at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:664)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:639)
	at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:617)
	at hudson.model.Build$RunnerImpl.post2(Build.java:161)
	at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:586)
	at hudson.model.Run.run(Run.java:1400)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:146)
Caused by: java.io.IOException: Remote call on Runtime_zLinux_Slave failed
	at hudson.remoting.Channel.call(Channel.java:676)
	at hudson.FilePath.act(FilePath.java:747)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: org/apache/tools/ant/types/selectors/TokenizedPath
	at org.apache.tools.ant.DirectoryScanner.scan(DirectoryScanner.java:869)
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:490)
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:451)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:105)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:87)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:1980)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:283)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:452)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
	at java.util.concurrent.FutureTask.run(FutureTask.java:149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:897)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:919)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:736)
</pre>
</div></div>

<p>The JRE used on the build slave is "IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux s390x-64".</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 1.417<br/>
z/Linux (s390x) 64bit
```
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/oleg_nenashev.png" title="oleg_nenashev's avatar" /> oleg_nenashev's <a href="https://issues.jenkins.io/browse/JENKINS-10059?focusedId=347007&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-347007">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Too old, no recent reports</p>
</pre>
</details>

</details>
<p>Too old, no recent reports</p>
