### ISSUE TITLE
[JENKINS-21664] Plugins with optional dependencies and compiled with Java6 cause Exception in loading

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-15#11513]
<p>Steps to produce the problem:</p>
<ol>
	<li>Install Copy Artifact</li>
	<li>Disable Maven plugin</li>
	<li>Restart Jenkins</li>
	<li>Fails to load Copy Artifact with: (full stacktrace is attached)

<pre>
1) Error injecting constructor, java.lang.NoClassDefFoundError: hudson/maven/MavenBuild
  at hudson.plugins.copyartifact.CopyArtifact$DescriptorImpl.<init>(Unknown Source)
</pre></li>
</ol>

<p>I found followings:</p>
<ul>
	<li>This can be reproduced when I package Copy Artifact with jdk 1.6.</li>
	<li>This cannot be reproduced when I package Copy Artifact with jdk 1.7.</li>
</ul>

<p>It seems that something strange happens in Jenkins plugin loading system.<br/>
It may be a problem with guice 4.0 introduced in <a href="https://github.com/jenkinsci/jenkins/commit/aea10298fed376979e41f4482dd6f2a916f4b23f" class="external-link" target="_blank" rel="nofollow noopener">aea10298</a> (may be guice does not work with Java1.6).</p>

<p>What I will do are:</p>
<ul>
	<li>Create a minimum plugin to reproduce the problem.</li>
	<li>Test what happens if reverted aea10298.</li>
	<li>Test what happens if downgrade guice to guice 3.0 (fails to compile?)</li>
</ul>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ikedam">ikedam</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-21664" target="_blank">Plugins with optional dependencies and compiled with Java6 cause Exception in loading</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ikedam">ikedam</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2014-02-10T14:08:54+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-11-16
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Steps to produce the problem:</p>
<ol>
	<li>Install Copy Artifact</li>
	<li>Disable Maven plugin</li>
	<li>Restart Jenkins</li>
	<li>Fails to load Copy Artifact with: (full stacktrace is attached)
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">1) Error injecting constructor, java.lang.NoClassDefFoundError: hudson/maven/MavenBuild
  at hudson.plugins.copyartifact.CopyArtifact$DescriptorImpl.&lt;init&gt;(Unknown Source)
</pre>
</div></div></li>
</ol>

<p>I found followings:</p>
<ul>
	<li>This can be reproduced when I package Copy Artifact with jdk 1.6.</li>
	<li>This cannot be reproduced when I package Copy Artifact with jdk 1.7.</li>
</ul>

<p>It seems that something strange happens in Jenkins plugin loading system.
It may be a problem with guice 4.0 introduced in <a href="https://github.com/jenkinsci/jenkins/commit/aea10298fed376979e41f4482dd6f2a916f4b23f" class="external-link" target="_blank" rel="nofollow noopener">aea10298</a> (may be guice does not work with Java1.6).</p>

<p>What I will do are:</p>
<ul>
	<li>Create a minimum plugin to reproduce the problem.</li>
	<li>Test what happens if reverted aea10298.</li>
	<li>Test what happens if downgrade guice to guice 3.0 (fails to compile?)</li>
</ul>
</pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 1.532, 1.549<br/>
Copy Artifact 1.28
```
</details>
<details><summary><i>1 attachment</i></summary>

- [stacktrace.log](https://issues.jenkins.io/secure/attachment/25249/stacktrace.log)
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>ikedam's <a href="https://issues.jenkins.io/browse/JENKINS-21664?focusedId=194516&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-194516">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>when depending on maven-plugin...</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>JDK Jenkins</th>
<th class='confluenceTh'>1.523    </th>
<th class='confluenceTh'>1.524    </th>
</tr>
<tr>
<th class='confluenceTh'>1.6        </th>
<td class='confluenceTd'>&nbsp;</td>
<td class='confluenceTd'>reproduce </td>
</tr>
<tr>
<th class='confluenceTh'>1.7        </th>
<td class='confluenceTd'>&nbsp;</td>
<td class='confluenceTd'>&nbsp;</td>
</tr>
</tbody></table>
</div>


<p>when depending on an original plugin...</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>JDK Jenkins</th>
<th class='confluenceTh'>1.523    </th>
<th class='confluenceTh'>1.524    </th>
</tr>
<tr>
<th class='confluenceTh'>1.6        </th>
<td class='confluenceTd'>reproduce </td>
<td class='confluenceTd'>reproduce </td>
</tr>
<tr>
<th class='confluenceTh'>1.7        </th>
<td class='confluenceTd'>&nbsp;</td>
<td class='confluenceTd'>&nbsp;</td>
</tr>
</tbody></table>
</div>


<p>It seems nothing to do with guice...</p>
</pre>
</details>

</details>
<p>when depending on maven-plugin...</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>JDK Jenkins</th>
<th class='confluenceTh'>1.523    </th>
<th class='confluenceTh'>1.524    </th>
</tr>
<tr>
<th class='confluenceTh'>1.6</th>
<td class='confluenceTd'> </td>
<td class='confluenceTd'>reproduce </td>
</tr>
<tr>
<th class='confluenceTh'>1.7</th>
<td class='confluenceTd'> </td>
<td class='confluenceTd'> </td>
</tr>
</tbody></table>
</div>


<p>when depending on an original plugin...</p>
<div class='table-wrap'>
<table class='confluenceTable'><tbody>
<tr>
<th class='confluenceTh'>JDK Jenkins</th>
<th class='confluenceTh'>1.523    </th>
<th class='confluenceTh'>1.524    </th>
</tr>
<tr>
<th class='confluenceTh'>1.6</th>
<td class='confluenceTd'>reproduce </td>
<td class='confluenceTd'>reproduce </td>
</tr>
<tr>
<th class='confluenceTh'>1.7</th>
<td class='confluenceTd'> </td>
<td class='confluenceTd'> </td>
</tr>
</tbody></table>
</div>


<p>It seems nothing to do with guice...</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>ikedam's <a href="https://issues.jenkins.io/browse/JENKINS-21664?focusedId=194519&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-194519">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Hmm... that difference seems caused by <a href="https://github.com/jenkinsci/jenkins/commit/a6926e1c51c0650a48dec68cbe402248742dd55c" class="external-link" target="_blank" rel="nofollow noopener">a6926e1c51c0650a48dec68cbe402248742dd55c</a>.
Installed, but disabled plugins are registered to class loaders in Jenkins &lt; 1.524.</p>
</pre>
</details>

</details>
<p>Hmm... that difference seems caused by <a href="https://github.com/jenkinsci/jenkins/commit/a6926e1c51c0650a48dec68cbe402248742dd55c" class="external-link" target="_blank" rel="nofollow noopener">a6926e1c51c0650a48dec68cbe402248742dd55c</a>.<br/>
Installed, but disabled plugins are registered to class loaders in Jenkins < 1.524.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>ikedam's <a href="https://issues.jenkins.io/browse/JENKINS-21664?focusedId=194538&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-194538">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>This problem seems caused for <tt>Class#getMethod("getDescriptor")</tt> in <tt>Descriptor#&lt;init&gt;</tt> tries to load classes in optional depended plugins.
It must be a problem with JDK.</p>

<p>I'm not sure why but I cannot reproduce this behavior without Jenkins.</p>
</pre>
</details>

</details>
<p>This problem seems caused for <tt>Class#getMethod("getDescriptor")</tt> in <tt>Descriptor#<init></tt> tries to load classes in optional depended plugins.<br/>
It must be a problem with JDK.</p>

<p>I'm not sure why but I cannot reproduce this behavior without Jenkins.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>ikedam's <a href="https://issues.jenkins.io/browse/JENKINS-21664?focusedId=194541&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-194541">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>I finally found the root cause.
Upcasting in codes cause class loading:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">public</span> void doSomething()
{
  <span class="code-keyword">if</span>(Jenkins.getInstance().getPlugin(<span class="code-quote">"dependee"</span>))
  {
    Derived d = somemethod();
    Base b = (Derive)d; <span class="code-comment">// &lt;- This causes load Derive even not executing doSomething().
</span>  }
}
</pre>
</div></div>

<p>and in Java6,</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">for</span>(Base b: getDerivedList())
{
  someMethodForBase(b);
}
</pre>
</div></div>

<p>This code is compiled as following:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">for</span>(Derived b: getDerivedList()) <span class="code-comment">// &lt;- Base is changed to Derived
</span>{
  someMethodForBase(b); <span class="code-comment">// Here causes upcasting.
</span>}
</pre>
</div></div>

<p>There are some exceptions:</p>
<ul>
	<li>Upcasting to <tt>Object</tt> does not cause class loading.</li>
	<li>Conversion between generic types does not cause class loading. (as generic types are completely ignored in execution time)
	<ul>
		<li><tt>Base b = derivedList.get( i );</tt> does not cause class loading.</li>
		<li><tt>Base b = derivedIterator.next();</tt> does not cause class loading.</li>
	</ul>
	</li>
</ul>

</pre>
</details>

</details>
<p>I finally found the root cause.<br/>
Upcasting in codes cause class loading:</p>

<pre>
<span class="code-keyword">public</span> void doSomething()
{
  <span class="code-keyword">if</span>(Jenkins.getInstance().getPlugin(<span class="code-quote">"dependee"</span>))
  {
    Derived d = somemethod();
    Base b = (Derive)d; <span class="code-comment">// <- This causes load Derive even not executing doSomething().
</span>  }
}
</pre>

<p>and in Java6,</p>

<pre>
<span class="code-keyword">for</span>(Base b: getDerivedList())
{
  someMethodForBase(b);
}
</pre>

<p>This code is compiled as following:</p>

<pre>
<span class="code-keyword">for</span>(Derived b: getDerivedList()) <span class="code-comment">// <- Base is changed to Derived
</span>{
  someMethodForBase(b); <span class="code-comment">// Here causes upcasting.
</span>}
</pre>

<p>There are some exceptions:</p>
<ul>
	<li>Upcasting to <tt>Object</tt> does not cause class loading.</li>
	<li>Conversion between generic types does not cause class loading. (as generic types are completely ignored in execution time)
	<ul>
		<li><tt>Base b = derivedList.get( i );</tt> does not cause class loading.</li>
		<li><tt>Base b = derivedIterator.next();</tt> does not cause class loading.</li>
	</ul>
	</li>
</ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>ikedam's <a href="https://issues.jenkins.io/browse/JENKINS-21664?focusedId=194586&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-194586">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>This is not a issue with Jenkins, but Java language feature.
I wrote a tips note for this problem:
<a href="https://wiki.jenkins-ci.org/display/JENKINS/Tips+for+optional+dependencies" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins-ci.org/display/JENKINS/Tips+for+optional+dependencies</a></p>
</pre>
</details>

</details>
<p>This is not a issue with Jenkins, but Java language feature.<br/>
I wrote a tips note for this problem:<br/>
<a href="https://wiki.jenkins-ci.org/display/JENKINS/Tips+for+optional+dependencies" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins-ci.org/display/JENKINS/Tips+for+optional+dependencies</a></p>

**Comment by jenkins-infra-bot** [comment]
<i>[Originally related to: <a href="https://github.com/timja-org/jenkins-gh-issues-poc-11-15/issues?q=in%3Atitle%20JENKINS-21274">JENKINS-21274</a>]</i>
